image: golang

variables:
  REGISTRY_IMAGE: asia.gcr.io/warung-support/${CI_PROJECT_NAME}

stages:
  - lint
  - test

unit_tests:
  stage: test
  script:
    - make test

lint_code:
  stage: lint
  script:
    - make lint