image: golang

variables:
  REGISTRY_IMAGE: asia.gcr.io/warung-support/${CI_PROJECT_NAME}

before_script:
  - mkdir -p $HOME/.docker
  - echo "$DOCKER_AUTH_CONFIG"
  - echo "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"

stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  script:
    - make test

build:
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  stage: build
  before_script:
    - mkdir -p /root/.docker
    - echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
  only:
    - master
  script:
    - /kaniko/executor --build-arg SSH_PRIVATE_KEY="$GIT_PRIVATE_KEY" --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination ${REGISTRY_IMAGE}:latest
  tags:
    - gke

deploy_dev:
  image: asia.gcr.io/warung-support/google-sdk:latest
  before_script:
    - mkdir -p $HOME/.docker
    - echo "$DOCKER_AUTH_CONFIG" >> "$HOME/.docker/config.json"
  stage: deploy
  variables:
    IMAGE_VERSION: latest
    IMAGE_NAME: ${CI_PROJECT_NAME}
  script:
    # Authenticate with GKE
    - echo $SERVICE_ACCOUNT_KEY > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project warung-development
    - gcloud config set container/cluster development-cluster
    - gcloud config set compute/zone asia-southeast1-b
    - gcloud container clusters get-credentials staging-cluster-nat-1  --zone asia-southeast1-b
    # Do the deployment
    - sed -ie "s/THIS_STRING_IS_REPLACED_DURING_BUILD/$CI_PIPELINE_ID/g" ./app-deploy.yml
    - cat ./app-deploy.yml | envsubst | envsubst | kubectl apply -f -

  only:
    - master